
import { useEffect } from 'react';
import { useToast } from '@/components/ui/use-toast';
import { generateStoryService } from '@/services/storyService';
import { IllustrationStyle } from '@/services/illustrationService';
import { useNavigate } from 'react-router-dom';
import { useLectoriaStore } from '@/store/useLectoriaStore';

export const useStoryGeneration = () => {
  const {
    // Données du héros
    heroName,
    heroAge,
    heroGender,
    heroTrait,
    // Éléments d'histoire
    selectedValues,
    selectedStoryElements,
    // Données de génération
    isGenerating,
    progress,
    storyPreview,
    fullStory,
    prompt,
    pageCount,
    illustrationUrl,
    illustrations,
    illustrationStyle,
    showBookPreview,
    // Méthodes
    setIsGenerating,
    setProgress,
    setStoryPreview,
    setFullStory,
    setPrompt,
    setPageCount,
    setIllustrationUrl,
    setIllustrations,
    setIllustrationStyle,
    setShowBookPreview,
    resetStoryData
  } = useLectoriaStore();
  
  const { toast } = useToast();
  const navigate = useNavigate();
  
  useEffect(() => {
    // Mettre à jour la progression pour cette étape
    setProgress(80);
  }, [setProgress]);

  const generateStory = async () => {
    setIsGenerating(true);
    setIllustrationUrl(null);
    setIllustrations([]);
    
    try {
      const childAge = heroAge ? parseInt(heroAge) : 6;

      // Auto-generate a prompt if none is provided
      const autoGeneratedPrompt = !prompt.trim() ? 
        `Une histoire personnalisée avec ${heroName || 'notre héros'} comme personnage principal` : 
        prompt;

      const result = await generateStoryService({
        prompt: autoGeneratedPrompt,
        pageCount,
        childAge,
        values: selectedValues,
        elements: selectedStoryElements,
        illustrationStyle,
        heroName,
        heroGender,
        heroAge,
        heroTrait
      });
      
      setFullStory(result.fullStory);
      setStoryPreview(result.storyPreview);
      setIllustrationUrl(result.illustrationUrl);
      
      if (result.illustrations && result.illustrations.length > 0) {
        setIllustrations(result.illustrations);
      }
      
      setProgress(100);
      
      toast({
        title: "Histoire générée !",
        description: `Ton histoire personnalisée est prête avec ${result.illustrations?.length || 0} illustrations. Découvre un aperçu et commande le livre complet !`,
      });
    } catch (error) {
      toast({
        title: "Erreur",
        description: "Il y a eu un problème lors de la génération de l'histoire.",
        variant: "destructive",
      });
      console.error("Erreur de génération:", error);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleContinue = () => {
    navigate('/offres-cadeaux');
  };

  const handleShare = () => {
    toast({
      title: "Partage",
      description: "Partagez l'aperçu de cette histoire avec vos proches !",
    });
  };

  const toggleBookPreview = () => {
    setShowBookPreview(!showBookPreview);
  };

  return {
    isGenerating,
    progress,
    storyPreview,
    fullStory,
    prompt,
    pageCount,
    illustrationUrl,
    illustrations,
    illustrationStyle,
    showBookPreview,
    setPrompt,
    setPageCount,
    setIllustrationStyle,
    generateStory,
    handleShare,
    resetStory: resetStoryData,
    toggleBookPreview,
    handleContinue
  };
};
