// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tigbprdphighswckymqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpZ2JwcmRwaGlnaHN3Y2t5bXFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTU4MjYsImV4cCI6MjA3MTI5MTgyNn0.zZPQ4HMzD5vTAM6IgzN9qqJlGbYMZ527-pCa64dM9MY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});